# -*- coding: utf-8 -*-
"""encadenament_endavant.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1yWWxJ3I9bR0id-u-YUP3ANyaO_R1TuTd
"""

BD = ['D','H','F']
target = 'A'
rules_used = []
target_found = False
no_rules_to_be_used = False
num_rules = 10

def rules(id_rule, BD):
    if id_rule == 1:
      if 'A' in BD and 'B' in BD:
        return True,  'E'
      else:
        return False, ''
    elif id_rule == 2:
      if 'A' in BD and 'C' in BD:
        return True, 'F'
      else:
        return False, ''
    elif id_rule == 3:
      if  'A' not in BD and 'B' in BD:
        return True, 'D'
      else:
        return False, ''
    elif id_rule == 4:
      if 'A' not in BD and 'B' not in BD:
        return True, 'E'
      else:
        return False, ''
    elif id_rule == 5:
       if 'B' in BD and 'C'  in BD:
        return True, 'F'
       else:
        return False, ''
    elif id_rule == 6:
       if 'B' not in BD and 'C' not in BD:
        return True, 'notF'
       else:
        return False, ''
    elif id_rule == 7:   
       if 'D' in BD and 'F' not in BD:
        return True, 'H'
       else:
        return False, ''
    elif id_rule == 8:
       if 'D' in BD and 'F' in BD:
        return True, 'G'
       else:
        return False, ''
    elif id_rule == 9:
       if 'E' in BD and 'F' in BD:
        return True, 'H'
       else:
        return False, ''
    elif id_rule == 10:
       if 'E' in BD and  'F' not in BD:
        return True, 'G'
       else:
        return False, ''


def select_rule(valid_rules):
  return valid_rules[0]
  
while not target_found and not no_rules_to_be_used:
  valid_rules = []
  for ii in range(1, num_rules + 1):
    valid_rule, new_state = rules(ii,BD)
    if valid_rule and ii not in rules_used and new_state not in BD:
      valid_rules.append(ii)
  if len(valid_rules) > 0:
    selected_rule = select_rule(valid_rules)
    rules_used.append(selected_rule)
    valid_rule, new_state = rules(selected_rule,BD)
   

    if new_state=='notA':
       BD.remove('A')
 

    if new_state=='notB':
       BD.remove('B')
   
    if new_state=='notC':
       BD.remove('C')
    

    if new_state=='notD':
       BD.remove('D')
    
    if new_state=='notE':
       BD.remove('E')
 

    if new_state=='notF':
       BD.remove('F')
    
  
    print("selected_rule: " + str(selected_rule))
    print("BD: ")
    print(BD)
    if target in BD:
      target_found = True
      print("Target found!")
  else:
    no_rules_to_be_used = True
    print("Target not found and no rules can be used")
