# -*- coding: utf-8 -*-
"""encadenament_endavant.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1yWWxJ3I9bR0id-u-YUP3ANyaO_R1TuTd
"""


BD = ['D','H','F']
target = 'A'
rules_used = []
target_found = False
no_rules_to_be_used = False
num_rules = 9

def rules(id_rule, BD):
    if id_rule == 1:
      if 'G' in BD and 'D' in BD:
        return True,  'B'
      else:
        return False, ''
    elif id_rule == 2:
      if 'F' in BD and 'G' not in BD:
        return True, 'notE'
      else:
        return False, ''
    elif id_rule == 3:
      if  'H' in BD:
        return True, 'E'
      else:
        return False, ''
    elif id_rule == 4:
      if 'I' not in BD:
        return True, 'I'
      else:
        return False, ''
    elif id_rule == 5:
       if 'F' in BD:
        return True, 'C'
       else:
        return False, ''
    elif id_rule == 6:
       if 'I' not in BD and 'A' in BD:
        return True, 'notA'
       else:
        return False, ''
    elif id_rule == 7:   
       if 'I' in BD:
        return True, 'notE'
       else:
        return False, ''
    elif id_rule == 8:
       if 'G' in BD:
        return True, 'C'
       else:
        return False, ''
    elif id_rule == 9:
       if 'C' in BD:
        return True, 'A'
       else:
        return False, ''
  


def select_rule(valid_rules):
  return valid_rules[0]
  
while not target_found and not no_rules_to_be_used:
  valid_rules = []
  for ii in range(1, num_rules + 1):
    valid_rule, new_state = rules(ii,BD)
    if valid_rule and ii not in rules_used and new_state not in BD:
      valid_rules.append(ii)
  if len(valid_rules) > 0:
    selected_rule = select_rule(valid_rules)
    rules_used.append(selected_rule)
    valid_rule, new_state = rules(selected_rule,BD)
    

    if new_state=='notE':
       BD.remove('E')
    else:
       BD.append(new_state)
    
  
    print("selected_rule: " + str(selected_rule))
    print("BD: ")
    print(BD)
    if target in BD:
      target_found = True
      print("Target found!")
  else:
    no_rules_to_be_used = True
    print("Target not found and no rules can be used")
